id: P006859
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:03.532817
source_metadata:
  id: bdr:W1KG9608
  title: ལྷ་ས་གཙུག་ལག་ཁང་གི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་ཆ།
  author: ''
  volumes:
    bc51b45ed64547c4a99e56a0a2e97a4f:
      image_group_id: I1KG9613
      title: ''
      volume_number: 1
      total_pages: 89
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
