id: I1331C862
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:28:15+00:00'
last_modified: '2022-06-08T08:45:57.609375+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9608
  title: ལྷ་ས་གཙུག་ལག་ཁང་གི་ལོ་རྒྱུས་དཔྱད་གཞིའི་ཡིག་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B626:
      image_group_id: I1KG9613
      title: ''
      total_pages: 89
      order: 1
      base_file: B626.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
